version: "3.9"
services:

  kvas:
    image: "${IMAGE_NAME}"
    container_name: "${CONTAINER_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
        NAME: "${NAME}"

    volumes:
      - .:/apps/kvas

    environment:
      VERSION: "${VERSION}"
      UID: "${UID}"
      GID: "${GID}"
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      USER: "${USER}"

    restart: "unless-stopped"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

