#!/bin/sh
# ------------------------------------------------------------------------------------------
#
# 	ПРОЕКТ КВАС
#
# ------------------------------------------------------------------------------------------
# 	Данный файл служит для
#	В случае, если созданное подключение еще нет в списке интерфейсов,
#	то добавляем его в файл /opt/etc/inface_equals "${INFACE_NAMES_FILE}"
# ------------------------------------------------------------------------------------------
#	Разработчик: kvas@zeleza.ru
#	Дата: 18/01/2024
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------------------

if [ "${1}" = "hook" ] ; then
    # Подключаем глобальные параметры
	# shellcheck source=opt\bin\libs\env.sh
    . /opt/apps/kvas/bin/libs/env.sh

    # Проверка обязательных переменных
    if [ -z "$id" ] || [ -z "$system_name" ]; then
        exit 1
    fi

    json=$(curl -s "http://localhost:79/rci/show/interface/${id}")

    if [ -n "$json" ]; then
        global=$(echo "$json" | jq -r '.global // empty')
        if [ "$global" = "false" ]; then
            if ! grep -q "${id}" "${INFACE_NAMES_FILE}"; then
                desc=$(echo "$json" | jq -r '.description')
                echo "${id}|${system_name}|${desc}" >> "${INFACE_NAMES_FILE}"
            fi
        fi
    fi
fi