#!/bin/sh

# shellcheck source=opt\bin\libs\ndm_d
. /opt/apps/kvas/bin/libs/ndm_d

if [ "${1}" = "hook" ] && [ "${change}" = "link" ] ; then

#	 Действия для подключений PPTP|L2TP, которое подключено к провайдеру
	 if [[ ${id} =~ 'PPTP|L2TP' ]] && is_cli_iface_global "${id}"; then
		#	В случае отключения PPTP|L2TP соединения через основной интерфейс
		#	проще говоря, в случае если подключение к интернету осуществляется
		#	через PPTP|L2TP соединение и оно прервалось	- ставим флаг, в виде создания файла
		tmp_file=/opt/tmp/sub_connection
		
		case "${connected}-${link}-${up}" in
			"no-down-down" )
				touch "${tmp_file}"
			;;
			"yes-up-up" )
				[ -f "${tmp_file}" ] && {
					# После отключения PPTP|L2TP (которое используется для подключения к провайдеру)
					# и при наличии файла tmp_file - переустанавливаем ipset правила для восстановления
					cmd_vpn_iptable_reset &> /dev/null
					logger -t "КВАС"  "Соединение ${id} успешно подключено, правила восстановлены!"
					rm -f "${tmp_file}"
				}
			;;
		esac
	fi

#	Действия для всех остальных подключений
	cli_inface=$(get_config_value "INFACE_CLI")
	if [ "$id" = "$cli_inface" ]; then
		case "${connected}-${link}-${up}" in
			"no-down-down" )
				#link_reboot "" &> /dev/null
				logger -t "КВАС"  "Соединение ${id} прервано. Правила и таблицы НЕ очищены!"
			;;
			"yes-up-up" )
				cmd_vpn_iptable_reset &> /dev/null
				logger -t "КВАС"  "Соединение ${id} установлено. Правила и таблицы пересозданы."
			;;
		esac
	fi
fi