name: Docker KVAS Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v3
    - name: Собираем образ для КВАСА
      run: docker build . --file Dockerfile --tag kvas_develop:$(date +%s)
